TOON_DATA = {
    'GRIEVOUS': {'name': 'General Grievous', 'type': 'toon', 'alias': ['grievous', 'general grievous', 'gg'],
                 'icon': 'https://swgoh.gg/static/img/assets/tex.charui_grievous.png'},
    'HUMANTHUG': {'name': 'Mob Enforcer', 'type': 'toon', 'alias': ['mob enforcer', 'me'],
                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_thug_female_01.png'},
    'ADMINISTRATORLANDO': {'name': 'Lando Calrissian', 'type': 'toon', 'alias': ['lando', 'lando calrissian'],
                           'icon': 'https://swgoh.gg/static/img/assets/tex.charui_landobespin.png'},
    'XWINGRED2': {'name': "Wedge Antilles's X-wing", 'type': 'ship',
                  'alias': ['wedge antilles xwing', 'xwing', 'wedge', 'wedge antilles']},
    'PLOKOON': {'name': 'Plo Koon', 'type': 'toon', 'alias': ['plo', 'plo koon', 'koon']},
    'REY': {'name': 'Rey (Scavenger)', 'type': 'toon', 'alias': ['rey', 'scavenger rey']},
    'HK47': {'name': 'HK-47', 'type': 'toon', 'alias': ['hk47']},
    'KYLOREN': {'name': 'Kylo Ren', 'type': 'toon', 'alias': ['kylo', 'kylo ren']},
    'TIEFIGHTERIMPERIAL': {'name': 'Imperial Tie Fighter', 'type': 'ship',
                           'alias': ['imperial tie fighter', 'tie', 'tie fighter']},
    'PHANTOM2': {'name': 'Phantom II', 'type': 'ship', 'alias': ['phantom', 'phantom ii', 'phantom 2']},
    'PAO': {'name': 'Pao', 'type': 'toon', 'alias': ['pao']},
    'ARC170REX': {'name': "Rex's ARC-170", 'type': 'ship', 'alias': ['rex', 'arc170']},
    'CT7567': {'name': 'CT-7567 "Rex"', 'type': 'toon', 'alias': ['rex', 'ct7567']},
    'MAGNAGUARD': {'name': 'IG-100 MagnaGuard', 'type': 'toon', 'alias': ['ig100', 'magnaguard', 'ig100 magnaguard']},
    'ROYALGUARD': {'name': 'Royal Guard', 'type': 'toon', 'alias': ['rg', 'royal guard']},
    'DARTHNIHILUS': {'name': 'darth nihilus', 'type': 'toon', 'alias': ['dn', 'darth nihilus', 'nihilus']},
    'EWOKELDER': {'name': 'Ewok Elder', 'type': 'toon', 'alias': ['ewok elder', 'ewok', 'ee']},
    'OLDBENKENOBI': {'name': 'Obi-Wan Kenobi (Old Ben)', 'type': 'toon',
                     'alias': ['ob', 'ben', 'old ben', 'old ben kenobi', 'kenobi']},
    'ASAJVENTRESS': {'name': 'Asajj Ventress', 'type': 'toon', 'alias': ['asajj', 'asajj ventress', 'av']},
    'LUKESKYWALKER': {'name': 'Luke Skywalker (Farmboy)', 'type': 'toon',
                      'alias': ['luke', 'luke skywalker', 'farmboy', 'luke skywalker farmboy']},
    'DAKA': {'name': 'Old Daka', 'type': 'toon', 'alias': ['daka', 'old daka', 'od']},
    'CC2224': {'name': 'CC-2224 "Cody"', 'type': 'toon', 'alias': ['cody', 'cc2224']},
    'ZAMWESELL': {'name': 'Zam Wesell', 'type': 'toon', 'alias': ['zam', 'zam zesell']},
    'QUIGONJINN': {'name': 'Qui-Gon Jinn', 'type': 'toon', 'alias': ['qgj', 'qui gon jinn']},
    'TUSKENSHAMAN': {'name': 'Tusken Shaman', 'type': 'toon', 'alias': ['tusken shaman', 'tusken', 'shaman', 'ts']},
    'BIGGSDARKLIGHTER': {'name': 'Biggs Darklighter', 'type': 'toon', 'alias': ['biggs', 'biggs darklighter']},
    'TUSKENRAIDER': {'name': 'Tusken Raider', 'type': 'toon', 'alias': ['tusker raider', 'tr']},
    'RESISTANCEPILOT': {'name': 'Resistance Pilot', 'type': 'toon', 'alias': ['rp', 'resistance pilot']},
    'GAMORREANGUARD': {'name': 'Gamorrean Guard', 'type': 'toon', 'alias': ['gamorrean guard', 'gg', 'hog']},
    'HOTHREBELSOLDIER': {'name': 'Hoth Rebel Soldier', 'type': 'toon', 'alias': ['hoth rebel soldier', 'hrs', 'hoth']},
    'XWINGBLACKONE': {'name': "Poe Dameron's X-wing", 'type': 'ship',
                      'alias': ['poe', 'poes xwing', 'poe damerons xwing']},
    'JAWASCAVENGER': {'name': 'Jawa Scavenger', 'type': 'toon', 'alias': ['jawa', 'jawa scavenger', 'js']},
    'SITHINFILTRATOR': {'name': 'Scimitar', 'type': 'toon', 'alias': ['scimitar']},
    'BODHIROOK': {'name': 'Bodhi Rook', 'type': 'toon', 'alias': ['bodhi', 'bodhi rook']},
    'STORMTROOPER': {'name': 'Stormtrooper', 'type': 'toon', 'alias': ['stormtrooper']},
    'SLAVE1': {'name': 'Slave I', 'type': 'ship', 'alias': ['slave', 'slave 1', 'slave i']},
    'CHOPPERS3': {'name': 'Chopper', 'type': 'toon', 'alias': ['chopper']},
    'GEONOSIANSOLDIER': {'name': 'Geonosian Soldier', 'type': 'toon', 'alias': ['geonosian soldier']},
    'UGNAUGHT': {'name': 'Ugnaught', 'type': 'toon', 'alias': ['ugnaught']},
    'MOTHERTALZIN': {'name': 'Mother Talzin', 'type': 'toon', 'alias': ['mother talzin', 'talzin']},
    'PHASMA': {'name': 'Captain Phasma', 'type': 'toon', 'alias': ['phasma', 'captain phasma']},
    'NIGHTSISTERSPIRIT': {'name': 'Nightsister Spirit', 'type': 'toon', 'alias': ['nightsister spirit']},
    'CLONEWARSCHEWBACCA': {'name': 'Clone Wars Chewbacca', 'type': 'toon',
                           'alias': ['chewbacca', 'clone wars chewbacca', 'chewie']},
    'TIEADVANCED': {'name': 'TIE Advanced x1', 'type': 'ship', 'alias': ['tie advanced x1', 'tie advanced']},
    'AHSOKATANO': {'name': 'Ahsoka Tano', 'type': 'toon', 'alias': ['ahsoka tano', 'ahsoka']},
    'CHIRRUTIMWE': {'name': 'Chirrut Îmwe', 'type': 'toon', 'alias': ['chirrut', 'chirrut imwe', 'imwe']},
    'FINN': {'name': 'Finn', 'type': 'toon', 'alias': ['finn']},
    'ZEBS3': {'name': 'Garazeb "Zeb" Orrelios', 'type': 'toon', 'alias': ['zeb']},
    'COMMANDERLUKESKYWALKER': {'name': 'Commander Luke Skywalker', 'type': 'toon',
                               'alias': ['cls', 'luke', 'commander luke', 'commander luke skywalker']},
    'MACEWINDU': {'name': 'Mace Windu', 'type': 'toon', 'alias': ['mace', 'mace windu']},
    'EWOKSCOUT': {'name': 'Ewok Scout', 'type': 'toon', 'alias': ['ewok scout']},
    'SNOWTROOPER': {'name': 'Snowtrooper', 'type': 'toon', 'alias': ['snowtrooper']},
    'DARTHSIDIOUS': {'name': 'Darth Sidious', 'type': 'toon', 'alias': ['darh sidious', 'sidious']},
    'BISTAN': {'name': 'Bistan', 'type': 'toon', 'alias': ['bistan']},
    'CORUSCANTUNDERWORLDPOLICE': {'name': 'Coruscant Underworld Police', 'type': 'toon',
                                  'alias': ['cup', 'coruscant underworld police'],
                                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_coruscantpolice.png'},
    'AAYLASECURA': {'name': 'Aayla Secura', 'type': 'toon', 'alias': ['aayla secura', 'aayla']},
    'POGGLETHELESSER': {'name': 'Poggle the Lesser', 'type': 'toon', 'alias': ['poggle', 'poggle the lesser']},
    'MAUL': {'name': 'Darth Maul', 'type': 'toon', 'alias': ['maul', 'darth maul', 'dm']},
    'LOBOT': {'name': 'Lobot', 'type': 'toon', 'alias': ['lobot']},
    'TIEFIGHTERFIRSTORDER': {'name': 'First Order TIE Fighter', 'type': 'toon',
                             'alias': ['first order tie fighter', 'fotf']},
    'JAWAENGINEER': {'name': 'Jawa Engineer', 'type': 'toon', 'alias': ['jawa engineer', 'jawa', 'engineer']},
    'GEONOSIANSPY': {'name': 'Geonosian Spy', 'type': 'toon', 'alias': ['geonosian spy']},
    'SITHTROOPER': {'name': 'Sith Trooper', 'type': 'toon', 'alias': ['sith trooper']},
    'COUNTDOOKU': {'name': 'Count Dooku', 'type': 'toon', 'alias': ['dooku', 'count dooku']},
    'HOTHLEIA': {'name': 'Rebel Officer Leia Organa', 'type': 'toon',
                 'alias': ['rolo', 'leia', 'rebel officer leia organa', 'organa']},
    'CHIEFNEBIT': {'name': 'Chief Nebit', 'type': 'toon', 'alias': ['chief nebit', 'nebit']},
    'XWINGRED3': {'name': "Biggs Darklighter's X-wing", 'type': 'ship',
                  'alias': ['biggs', 'biggs darklighter', 'biggs xwing', 'biggs darklighters xwing']},
    'CAPITALJEDICRUISER': {'name': 'Endurance', 'type': 'ship', 'alias': ['endurance']},
    'EMPERORPALPATINE': {'name': 'Emperor Palpatine', 'type': 'toon',
                         'alias': ['palpatine', 'ep', 'emperor palpatine']},
    'SHORETROOPER': {'name': 'Shoretrooper', 'type': 'toon', 'alias': ['shoretrooper']},
    'JEDIKNIGHTCONSULAR': {'name': 'Jedi Consular', 'type': 'toon', 'alias': ['jedi consular', 'jc']},
    'SITHASSASSIN': {'name': 'Sith Assassin', 'type': 'toon', 'alias': ['sith assassin']},
    'SMUGGLERCHEWBACCA': {'name': 'Veteran Smuggler Chewbacca', 'type': 'toon',
                          'alias': ['veteran smuggler chewbacca', 'veteran chewbacca', 'chewbacca', 'chewbie']},
    'SCARIFREBEL': {'name': 'Scarif Rebel Pathfinder', 'type': 'toon', 'alias': ['scarif rebel pathfinder', 'srp']},
    'JEDISTARFIGHTERAHSOKATANO': {'name': "Ahsoka Tano's Jedi Starfighter", 'type': 'ship',
                                  'alias': ['ahsoka tanos jedi starfighter', 'ahsoka', 'ahsoka tano']},
    'WICKET': {'name': 'Wicket', 'type': 'toon', 'alias': ['wicket']},
    'JEDIKNIGHTGUARDIAN': {'name': 'Jedi Knight Guardian', 'type': 'toon', 'alias': ['jedi knight guardian', 'jkg']},
    'SAVAGEOPRESS': {'name': 'Savage Opress', 'type': 'toon', 'alias': ['savage', 'savage opress']},
    'HOTHHAN': {'name': 'Captain Han Solo', 'type': 'toon', 'alias': ['hoth han', 'chs', 'captain han solo']},
    'CT210408': {'name': 'CT-21-0408 "Echo"', 'type': 'toon', 'alias': ['echo', 'ct-21-0408 echo']},
    'ANAKINKNIGHT': {'name': 'Jedi Knight Anakin', 'type': 'toon', 'alias': ['jedi knight anakin', 'jka']},
    'GEONOSIANSTARFIGHTER1': {'name': "Sun Fac's Geonosian Starfighter", 'type': 'ship',
                              'alias': ['sun fac', 'sun facs geonosian starfighter']},
    'JYNERSO': {'name': 'Jyn Erso', 'type': 'toon', 'alias': ['jyn', 'jyn erso']},
    'GAUNTLETSTARFIGHTER': {'name': 'Gauntlet Starfighter', 'type': 'ship',
                            'alias': ['gauntlet', 'gauntlet starfighter']},
    'CADBANE': {'name': 'Cad Bane', 'type': 'toon', 'alias': ['cad bane']},
    'PRINCESSLEIA': {'name': 'Princess Leia', 'type': 'toon', 'alias': ['princess leia', 'leia']},
    'JAWA': {'name': 'Jawa', 'type': 'toon', 'alias': ['jawa']},
    'KANANJARRUSS3': {'name': 'Kanan Jarrus', 'type': 'toon', 'alias': ['kanan', 'kanan jarrus']},
    'TIEFIGHTERPILOT': {'name': 'TIE Fighter Pilot', 'type': 'toon', 'alias': ['tfp', 'tie fighter pilot']},
    'URORRURRR': {'name': "URoRRuR'R'R", 'type': 'toon', 'alias': ['urorrurrr']},
    'ARC170CLONESERGEANT': {'name': "Clone Sergeant's ARC-170", 'type': 'ship',
                            'alias': ['clone sergeant', 'sergeant', 'clone sergeants arc170', 'arc170']},
    'BARRISSOFFEE': {'name': 'Barriss Offee', 'type': 'toon', 'alias': ['barriss', 'barriss offee']},
    'NIGHTSISTERINITIATE': {'name': 'Nightsister Initiate', 'type': 'toon', 'alias': ['nightsister initiate']},
    'EZRABRIDGERS3': {'name': 'Ezra Bridger', 'type': 'toon', 'alias': ['ezra', 'ezra bridger']},
    'DENGAR': {'name': 'Dengar', 'type': 'toon', 'alias': ['dengar']},
    'VEERS': {'name': 'General Veers', 'type': 'toon', 'alias': ['veers', 'general veers']},
    'RESISTANCETROOPER': {'name': 'Resistance Trooper', 'type': 'toon', 'alias': ['rp', 'resistance trooper']},
    'K2SO': {'name': 'K-2SO', 'type': 'toon', 'alias': ['k2so']},
    'BB8': {'name': 'BB-8', 'type': 'toon', 'alias': ['bb8']},
    'EETHKOTH': {'name': 'Eeth Koth', 'type': 'toon', 'alias': ['eeth', 'eeth koth']},
    'GRANDMOFFTARKIN': {'name': 'Grand Moff Tarkin', 'type': 'toon', 'alias': ['tarkin', 'grand moff tarkin']},
    'GHOST': {'name': 'Ghost', 'type': 'ship', 'alias': ['ghost']},
    'UWINGSCARIF': {'name': "Bistan's U-wing", 'type': 'ship', 'alias': ['bistans uwing', 'uwing']},
    'TIEREAPER': {'name': 'TIE Reaper', 'type': 'ship', 'alias': ['tie reaper']},
    'R2D2_LEGENDARY': {'name': 'R2-D2', 'type': 'toon', 'alias': ['r2d2', 'r2']},
    'DATHCHA': {'name': 'Dathcha', 'type': 'toon', 'alias': ['datcha']},
    'IG88': {'name': 'IG-88', 'type': 'toon', 'alias': ['ig88']},
    'GRANDMASTERYODA': {'name': 'Grand Master Yoda', 'type': 'toon', 'alias': ['yoda', 'grandmaster yoda']},
    'IMAGUNDI': {'name': 'Ima-Gun Di', 'type': 'toon', 'alias': ['ima gundi']},
    'XWINGRESISTANCE': {'name': 'Resistance X-wing', 'type': 'ship', 'alias': ['resistance xwing']},
    'FIRSTORDERTROOPER': {'name': 'First Order Stormtrooper', 'type': 'toon',
                          'alias': ['first order stormtrooper', 'fos']},
    'NIGHTSISTERZOMBIE': {'name': 'Nightsister Zombie', 'type': 'toon', 'alias': ['nightsister zombie']},
    'MILLENNIUMFALCONEP7': {'name': 'Millennium Falcon (Ep VII)', 'type': 'ship',
                            'alias': ['mf', 'millenium falcon', 'falcon']},
    'HERASYNDULLAS3': {'name': 'Hera Syndulla', 'type': 'toon', 'alias': ['hera', 'hera syndulla']},
    'HOTHREBELSCOUT': {'name': 'Hoth Rebel Scout', 'type': 'toon', 'alias': ['hrs', 'hoth rebel scout', 'hoth']},
    'LUMINARAUNDULI': {'name': 'Luminara Unduli', 'type': 'toon', 'alias': ['luminara unduli', 'luminara']},
    'CAPITALMONCALAMARICRUISER': {'name': 'Home One', 'type': 'ship', 'alias': ['home one']},
    'CAPITALSTARDESTROYER': {'name': 'Endurance', 'type': 'ship', 'alias': ['endurance']},
    'BOBAFETT': {'name': 'Boba Fett', 'type': 'toon', 'alias': ['boba', 'boba fett']},
    'CASSIANANDOR': {'name': 'Cassian Andor', 'type': 'toon', 'alias': ['cassian', 'cassian andor']},
    'JEDISTARFIGHTERCONSULAR': {'name': "Jedi Consular's Starfighter", 'type': 'ship',
                                'alias': ['jedi consulars starfighter']},
    'BLADEOFDORIN': {'name': "Plo Koon's Jedi Starfighter", 'type': 'ship',
                     'alias': ['plo koons jedi starfighter', 'plo koon']},
    'FIRSTORDEROFFICERMALE': {'name': 'First Order Officer', 'type': 'toon', 'alias': ['foo', 'first order officer']},
    'DIRECTORKRENNIC': {'name': 'Director Krennic', 'type': 'toon', 'alias': ['krennic', 'director krennic']},
    'IG86SENTINELDROID': {'name': 'IG-86 Sentinel Droid', 'type': 'toon', 'alias': ['ig86', 'ig86 sentinel droid']},
    'TEEBO': {'name': 'Teebo', 'type': 'toon', 'alias': ['teebo']},
    'GENERALKENOBI': {'name': 'General Kenobi', 'type': 'toon', 'alias': ['gk', 'general kenobi', 'kenobi']},
    'FULCRUMAHSOKA': {'name': 'Ahsoka Tano (Fulcrum)', 'type': 'toon',
                      'alias': ['ahsoka tano fulcrum', 'fulcrum', 'atf', 'hotsoka']},
    'ADMIRALACKBAR': {'name': 'Admiral Ackbar', 'type': 'toon', 'alias': ['ackbar', 'admiral ackbar', 'aa']},
    'LOGRAY': {'name': 'Logray', 'type': 'toon', 'alias': ['logray']},
    'IMPERIALSUPERCOMMANDO': {'name': 'Imperial Super Commando', 'type': 'toon',
                              'alias': ['imperial super commando', 'isc']},
    'GEONOSIANSTARFIGHTER3': {'name': "Geonosian Spy's Starfighter", 'type': 'ship',
                              'alias': ['geonosian spys starfighter', 'geonosian spy']},
    'GEONOSIANSTARFIGHTER2': {'name': "Geonosian Soldier's Starfighter", 'type': 'ship',
                              'alias': ['geonosian soldiers starfighter', 'geonosian soldier']},
    'NUTEGUNRAY': {'name': 'Nute Gunray', 'type': 'toon', 'alias': ['nute gunray', 'nute']},
    'NIGHTSISTERACOLYTE': {'name': 'Nightsister Acolyte', 'type': 'toon', 'alias': ['nightsister acolyte']},
    'SABINEWRENS3': {'name': 'Sabine Wren', 'type': 'toon', 'alias': ['sabine wren', 'sabine']},
    'SMUGGLERHAN': {'name': 'Veteran Smuggler Han Solo', 'type': 'toon',
                    'alias': ['veteran smuggler han solo', 'veteran han', 'vshs', 'han', 'han solo']},
    'POE': {'name': 'Poe Dameron', 'type': 'toon', 'alias': ['poe', 'poe dameron']},
    'MAGMATROOPER': {'name': 'Magmatrooper', 'type': 'toon', 'alias': ['magma trooper']},
    'COMMANDSHUTTLE': {'name': "Kylo Ren's Command Shuttle", 'type': 'ship', 'alias': ['command shuttle']},
    'CHIEFCHIRPA': {'name': 'Chief Chirpa', 'type': 'toon', 'alias': ['chief chirpa', 'chirpa']},
    'PAPLOO': {'name': 'Paploo', 'type': 'toon', 'alias': ['paploo']},
    'CLONESERGEANTPHASEI': {'name': 'Clone Sergeant - Phase I', 'type': 'toon',
                            'alias': ['clone sergeant phase i', 'clone sergeant']},
    'KITFISTO': {'name': 'Kit Fisto', 'type': 'toon', 'alias': ['kit fisto']},
    'GARSAXON': {'name': 'Gar Saxon', 'type': 'toon', 'alias': ['gar saxon']},
    'UWINGROGUEONE': {'name': "Cassian's U-wing", 'type': 'ship', 'alias': ['uwing', 'cassians uwing']},
    'CT5555': {'name': 'CT-5555 "Fives"', 'type': 'toon', 'alias': ['fives', 'five', 'ct5555 fives']},
    'GREEDO': {'name': 'Greedo', 'type': 'toon', 'alias': ['greedo']},
    'WEDGEANTILLES': {'name': 'Wedge Antilles', 'type': 'toon', 'alias': ['wedge', 'wedge antilles']},
    'SUNFAC': {'name': 'Sun Fac', 'type': 'toon', 'alias': ['sun fac']},
    'CAPITALCHIMAERA': {'name': 'Chimaera', 'type': 'ship', 'alias': ['chimaera']},
    'GRANDADMIRALTHRAWN': {'name': 'Grand Admiral Thrawn', 'type': 'toon', 'alias': ['thrawn', 'grand admiral thrawn']},
    'UMBARANSTARFIGHTER': {'name': 'Umbaran Starfighter', 'type': 'ship', 'alias': ['umbaran starfighter']},
    'BAZEMALBUS': {'name': 'Baze Malbus', 'type': 'toon', 'alias': ['baze', 'baze malbus']},
    'B2SUPERBATTLEDROID': {'name': 'B2 Super Battle Droid', 'type': 'toon', 'alias': ['b2', 'bé super battle droid']},
    'DEATHTROOPER': {'name': 'Death Trooper', 'type': 'toon', 'alias': ['death trooper']},
    'TALIA': {'name': 'Talia', 'type': 'toon', 'alias': ['talia']},
    'FIRSTORDERTIEPILOT': {'name': 'First Order TIE Pilot', 'type': 'toon', 'alias': ['first order tie pilot', 'fotp']},
    'VADER': {'name': 'Darth Vader', 'type': 'toon', 'alias': ['vader', 'darth vader', 'lord vader', 'death by tray'],
              'icon': 'https://swgoh.gg/static/img/assets/tex.charui_vader.png'},
    'STORMTROOPERHAN': {'name': 'Stormtrooper Han', 'type': 'toon',
                        'alias': ['sthan', 'stromtrooper han', 'han', 'han solo']},
    'HANSOLO': {'name': 'Han Solo', 'type': 'toon', 'alias': ['oghan', 'han solo', 'han', 'raid han']}
}
