TOON_DATA = {
    'GRIEVOUS': {'name': 'General Grievous', 'type': 'toon', 'alias': ['grievous', 'general grievous', 'gg'],
                 'icon': 'https://swgoh.gg/static/img/assets/tex.charui_grievous.png'},
    'HUMANTHUG': {'name': 'Mob Enforcer', 'type': 'toon', 'alias': ['mob enforcer', 'me'],
                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_thug_female_01.png'},
    'ADMINISTRATORLANDO': {'name': 'Lando Calrissian', 'type': 'toon', 'alias': ['lando', 'lando calrissian'],
                           'icon': 'https://swgoh.gg/static/img/assets/tex.charui_landobespin.png'},
    'XWINGRED2': {'name': "Wedge Antilles's X-wing", 'type': 'ship',
                  'alias': ['wedge antilles xwing', 'xwing', 'wedge', 'wedge antilles'],
                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_xwing_red2.png'},
    'PLOKOON': {'name': 'Plo Koon', 'type': 'toon', 'alias': ['plo', 'plo koon', 'koon'],
                'icon': 'https://swgoh.gg/static/img/assets/tex.charui_plokoon.png'},
    'REY': {'name': 'Rey (Scavenger)', 'type': 'toon', 'alias': ['rey', 'scavenger rey'],
            'icon': 'https://swgoh.gg/static/img/assets/tex.charui_reyjakku.png'},
    'HK47': {'name': 'HK-47', 'type': 'toon', 'alias': ['hk47'],
             'icon': 'https://swgoh.gg/static/img/assets/tex.charui_hk47.png'},
    'KYLOREN': {'name': 'Kylo Ren', 'type': 'toon', 'alias': ['kylo', 'kylo ren'],
                'icon': 'https://swgoh.gg/static/img/assets/tex.charui_kyloren.png'},
    'TIEFIGHTERIMPERIAL': {'name': 'Imperial Tie Fighter', 'type': 'ship',
                           'alias': ['imperial tie fighter', 'tie', 'tie fighter'],
                           'icon': 'https://swgoh.gg/static/img/assets/tex.charui_tiefighter.png'},
    'PHANTOM2': {'name': 'Phantom II', 'type': 'ship', 'alias': ['phantom', 'phantom ii', 'phantom 2'],
                 'icon': 'https://swgoh.gg/static/img/assets/tex.charui_phantom2.png'},
    'PAO': {'name': 'Pao', 'type': 'toon', 'alias': ['pao'],
            'icon': 'https://swgoh.gg/static/img/assets/tex.charui_pao.png'},
    'ARC170REX': {'name': "Rex's ARC-170", 'type': 'ship', 'alias': ['rex', 'arc170'],
                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_arc170_02.png'},
    'CT7567': {'name': 'CT-7567 "Rex"', 'type': 'toon', 'alias': ['rex', 'ct7567'],
               'icon': 'https://swgoh.gg/static/img/assets/tex.charui_trooperclone_rex.png'},
    'MAGNAGUARD': {'name': 'IG-100 MagnaGuard', 'type': 'toon', 'alias': ['ig100', 'magnaguard', 'ig100 magnaguard'],
                   'icon': 'https://swgoh.gg/static/img/assets/tex.charui_magnaguard.png'},
    'ROYALGUARD': {'name': 'Royal Guard', 'type': 'toon', 'alias': ['rg', 'royal guard'],
                   'icon': 'https://swgoh.gg/static/img/assets/tex.charui_royalguard.png'},
    'DARTHNIHILUS': {'name': 'darth nihilus', 'type': 'toon', 'alias': ['dn', 'darth nihilus', 'nihilus'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_nihilus.png'},
    'EWOKELDER': {'name': 'Ewok Elder', 'type': 'toon', 'alias': ['ewok elder', 'ewok', 'ee'],
                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_ewok_chief.png'},
    'OLDBENKENOBI': {'name': 'Obi-Wan Kenobi (Old Ben)', 'type': 'toon',
                     'alias': ['ob', 'ben', 'old ben', 'old ben kenobi', 'kenobi'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_obiwanep4.png'},
    'ASAJVENTRESS': {'name': 'Asajj Ventress', 'type': 'toon', 'alias': ['asajj', 'asajj ventress', 'av'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_ventress.png'},
    'LUKESKYWALKER': {'name': 'Luke Skywalker (Farmboy)', 'type': 'toon',
                      'alias': ['luke', 'luke skywalker', 'farmboy', 'luke skywalker farmboy'],
                      'icon': 'https://swgoh.gg/static/img/assets/tex.charui_luke_ep4.png'},
    'DAKA': {'name': 'Old Daka', 'type': 'toon', 'alias': ['daka', 'old daka', 'od'],
             'icon': 'https://swgoh.gg/static/img/assets/tex.charui_daka.png'},
    'CC2224': {'name': 'CC-2224 "Cody"', 'type': 'toon', 'alias': ['cody', 'cc2224'],
               'icon': 'https://swgoh.gg/static/img/assets/tex.charui_trooperclone_cody.png'},
    'ZAMWESELL': {'name': 'Zam Wesell', 'type': 'toon', 'alias': ['zam', 'zam zesell'],
                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_zamwesell.png'},
    'QUIGONJINN': {'name': 'Qui-Gon Jinn', 'type': 'toon', 'alias': ['qgj', 'qui gon jinn'],
                   'icon': 'https://swgoh.gg/static/img/assets/tex.charui_quigon.png'},
    'TUSKENSHAMAN': {'name': 'Tusken Shaman', 'type': 'toon', 'alias': ['tusken shaman', 'tusken', 'shaman', 'ts'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_tuskenshaman.png'},
    'BIGGSDARKLIGHTER': {'name': 'Biggs Darklighter', 'type': 'toon', 'alias': ['biggs', 'biggs darklighter'],
                         'icon': 'https://swgoh.gg/static/img/assets/tex.charui_rebelpilot_biggs.png'},
    'TUSKENRAIDER': {'name': 'Tusken Raider', 'type': 'toon', 'alias': ['tusker raider', 'tr'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_tuskenraider.png'},
    'RESISTANCEPILOT': {'name': 'Resistance Pilot', 'type': 'toon', 'alias': ['rp', 'resistance pilot'],
                        'icon': 'https://swgoh.gg/static/img/assets/tex.charui_resistancepilot.png'},
    'GAMORREANGUARD': {'name': 'Gamorrean Guard', 'type': 'toon', 'alias': ['gamorrean guard', 'gg', 'hog'],
                       'icon': 'https://swgoh.gg/static/img/assets/tex.charui_gamorreanguard.png'},
    'HOTHREBELSOLDIER': {'name': 'Hoth Rebel Soldier', 'type': 'toon', 'alias': ['hoth rebel soldier', 'hrs', 'hoth'],
                         'icon': 'https://swgoh.gg/static/img/assets/tex.charui_rebelhoth.png'},
    'XWINGBLACKONE': {'name': "Poe Dameron's X-wing", 'type': 'ship',
                      'alias': ['poe', 'poes xwing', 'poe damerons xwing'],
                      'icon': 'https://swgoh.gg/static/img/assets/tex.charui_xwing_blackone.png'},
    'JAWASCAVENGER': {'name': 'Jawa Scavenger', 'type': 'toon', 'alias': ['jawa', 'jawa scavenger', 'js'],
                      'icon': 'https://swgoh.gg/static/img/assets/tex.charui_jawa_scavenger.png'},
    'SITHINFILTRATOR': {'name': 'Scimitar', 'type': 'toon', 'alias': ['scimitar'],
                        'icon': 'https://swgoh.gg/static/img/assets/tex.charui_sithinfiltrator.png'},
    'BODHIROOK': {'name': 'Bodhi Rook', 'type': 'toon', 'alias': ['bodhi', 'bodhi rook'],
                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_bodhi.png'},
    'STORMTROOPER': {'name': 'Stormtrooper', 'type': 'toon', 'alias': ['stormtrooper'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_trooperstorm.png'},
    'SLAVE1': {'name': 'Slave I', 'type': 'ship', 'alias': ['slave', 'slave 1', 'slave i'],
               'icon': 'https://swgoh.gg/static/img/assets/tex.charui_slave1.png'},
    'CHOPPERS3': {'name': 'Chopper', 'type': 'toon', 'alias': ['chopper'],
                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_chopper.png'},
    'GEONOSIANSOLDIER': {'name': 'Geonosian Soldier', 'type': 'toon', 'alias': ['geonosian soldier'],
                         'icon': 'https://swgoh.gg/static/img/assets/tex.charui_geonosian_soldier.png'},
    'UGNAUGHT': {'name': 'Ugnaught', 'type': 'toon', 'alias': ['ugnaught'],
                 'icon': 'https://swgoh.gg/static/img/assets/tex.charui_ugnaught.png'},
    'MOTHERTALZIN': {'name': 'Mother Talzin', 'type': 'toon', 'alias': ['mother talzin', 'talzin'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_nightsisters_talzin.png'},
    'PHASMA': {'name': 'Captain Phasma', 'type': 'toon', 'alias': ['phasma', 'captain phasma'],
               'icon': 'https://swgoh.gg/static/img/assets/tex.charui_phasma.png'},
    'NIGHTSISTERSPIRIT': {'name': 'Nightsister Spirit', 'type': 'toon', 'alias': ['nightsister spirit'],
                          'icon': 'https://swgoh.gg/static/img/assets/tex.charui_nightsisters_wraith.png'},
    'CLONEWARSCHEWBACCA': {'name': 'Clone Wars Chewbacca', 'type': 'toon',
                           'alias': ['chewbacca', 'clone wars chewbacca', 'chewie'],
                           'icon': 'https://swgoh.gg/static/img/assets/tex.charui_chewbacca.png'},
    'TIEADVANCED': {'name': 'TIE Advanced x1', 'type': 'ship', 'alias': ['tie advanced x1', 'tie advanced'],
                    'icon': 'https://swgoh.gg/static/img/assets/tex.charui_tieadvanced.png'},
    'AHSOKATANO': {'name': 'Ahsoka Tano', 'type': 'toon', 'alias': ['ahsoka tano', 'ahsoka'],
                   'icon': 'https://swgoh.gg/static/img/assets/tex.charui_ahsoka.png'},
    'CHIRRUTIMWE': {'name': 'Chirrut Îmwe', 'type': 'toon', 'alias': ['chirrut', 'chirrut imwe', 'imwe'],
                    'icon': 'https://swgoh.gg/static/img/assets/tex.charui_chirrut.png'},
    'FINN': {'name': 'Finn', 'type': 'toon', 'alias': ['finn'],
             'icon': 'https://swgoh.gg/static/img/assets/tex.charui_finnjakku.png'},
    'ZEBS3': {'name': 'Garazeb "Zeb" Orrelios', 'type': 'toon', 'alias': ['zeb'],
              'icon': 'https://swgoh.gg/static/img/assets/tex.charui_zeb_s3.png'},
    'COMMANDERLUKESKYWALKER': {'name': 'Commander Luke Skywalker', 'type': 'toon',
                               'alias': ['cls', 'luke', 'commander luke', 'commander luke skywalker'],
                               'icon': 'https://swgoh.gg/static/img/assets/tex.charui_lukebespin.png'},
    'MACEWINDU': {'name': 'Mace Windu', 'type': 'toon', 'alias': ['mace', 'mace windu'],
                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_macewindu.png'},
    'EWOKSCOUT': {'name': 'Ewok Scout', 'type': 'toon', 'alias': ['ewok scout'],
                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_ewok_scout.png'},
    'SNOWTROOPER': {'name': 'Snowtrooper', 'type': 'toon', 'alias': ['snowtrooper'],
                    'icon': 'https://swgoh.gg/static/img/assets/tex.charui_troopersnow.png'},
    'DARTHSIDIOUS': {'name': 'Darth Sidious', 'type': 'toon', 'alias': ['darh sidious', 'sidious'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_sidious.png'},
    'BISTAN': {'name': 'Bistan', 'type': 'toon', 'alias': ['bistan'],
               'icon': 'https://swgoh.gg/static/img/assets/tex.charui_bistan.png'},
    'CORUSCANTUNDERWORLDPOLICE': {'name': 'Coruscant Underworld Police', 'type': 'toon',
                                  'alias': ['cup', 'coruscant underworld police'],
                                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_coruscantpolice.png'},
    'AAYLASECURA': {'name': 'Aayla Secura', 'type': 'toon', 'alias': ['aayla secura', 'aayla'],
                    'icon': 'https://swgoh.gg/static/img/assets/tex.charui_aaylasecura.png'},
    'POGGLETHELESSER': {'name': 'Poggle the Lesser', 'type': 'toon', 'alias': ['poggle', 'poggle the lesser'],
                        'icon': 'https://swgoh.gg/static/img/assets/tex.charui_geonosian_poggle.png'},
    'MAUL': {'name': 'Darth Maul', 'type': 'toon', 'alias': ['maul', 'darth maul', 'dm'],
             'icon': 'https://swgoh.gg/static/img/assets/tex.charui_maul.png'},
    'LOBOT': {'name': 'Lobot', 'type': 'toon', 'alias': ['lobot'],
              'icon': 'https://swgoh.gg/static/img/assets/tex.charui_lobot.png'},
    'TIEFIGHTERFIRSTORDER': {'name': 'First Order TIE Fighter', 'type': 'toon',
                             'alias': ['first order tie fighter', 'fotf'],
                             'icon': 'https://swgoh.gg/static/img/assets/tex.charui_firstorder_tiefighter.png'},
    'JAWAENGINEER': {'name': 'Jawa Engineer', 'type': 'toon', 'alias': ['jawa engineer', 'jawa', 'engineer'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_jawa_engineer.png'},
    'GEONOSIANSPY': {'name': 'Geonosian Spy', 'type': 'toon', 'alias': ['geonosian spy'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_geonosian_spy.png'},
    'SITHTROOPER': {'name': 'Sith Trooper', 'type': 'toon', 'alias': ['sith trooper'],
                    'icon': 'https://swgoh.gg/static/img/assets/tex.charui_sithtrooper.png'},
    'COUNTDOOKU': {'name': 'Count Dooku', 'type': 'toon', 'alias': ['dooku', 'count dooku'],
                   'icon': 'https://swgoh.gg/static/img/assets/tex.charui_dooku.png'},
    'HOTHLEIA': {'name': 'Rebel Officer Leia Organa', 'type': 'toon',
                 'alias': ['rolo', 'leia', 'rebel officer leia organa', 'organa'],
                 'icon': 'https://swgoh.gg/static/img/assets/tex.charui_leiahoth.png'},
    'CHIEFNEBIT': {'name': 'Chief Nebit', 'type': 'toon', 'alias': ['chief nebit', 'nebit'],
                   'icon': 'https://swgoh.gg/static/img/assets/tex.charui_jawa_nebit.png'},
    'XWINGRED3': {'name': "Biggs Darklighter's X-wing", 'type': 'ship',
                  'alias': ['biggs', 'biggs darklighter', 'biggs xwing', 'biggs darklighters xwing'],
                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_xwing_red3.png'},
    'CAPITALJEDICRUISER': {'name': 'Endurance', 'type': 'ship', 'alias': ['endurance'],
                           'icon': 'https://swgoh.gg/static/img/assets/tex.charui_venator.png'},
    'EMPERORPALPATINE': {'name': 'Emperor Palpatine', 'type': 'toon',
                         'alias': ['palpatine', 'ep', 'emperor palpatine'],
                         'icon': 'https://swgoh.gg/static/img/assets/tex.charui_palpatineemperor.png'},
    'SHORETROOPER': {'name': 'Shoretrooper', 'type': 'toon', 'alias': ['shoretrooper'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_troopershore.png'},
    'JEDIKNIGHTCONSULAR': {'name': 'Jedi Consular', 'type': 'toon', 'alias': ['jedi consular', 'jc'],
                           'icon': 'https://swgoh.gg/static/img/assets/tex.charui_jedi_consular_03.png'},
    'SITHASSASSIN': {'name': 'Sith Assassin', 'type': 'toon', 'alias': ['sith assassin'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_sithassassin.png'},
    'SMUGGLERCHEWBACCA': {'name': 'Veteran Smuggler Chewbacca', 'type': 'toon',
                          'alias': ['veteran smuggler chewbacca', 'veteran chewbacca', 'chewbacca', 'chewbie'],
                          'icon': 'https://swgoh.gg/static/img/assets/tex.charui_tfa_chewbacca.png'},
    'SCARIFREBEL': {'name': 'Scarif Rebel Pathfinder', 'type': 'toon', 'alias': ['scarif rebel pathfinder', 'srp'],
                    'icon': 'https://swgoh.gg/static/img/assets/tex.charui_rebel_scarif.png'},
    'JEDISTARFIGHTERAHSOKATANO': {'name': "Ahsoka Tano's Jedi Starfighter", 'type': 'ship',
                                  'alias': ['ahsoka tanos jedi starfighter', 'ahsoka', 'ahsoka tano'],
                                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_jedi_fighter_ahsoka.png'},
    'WICKET': {'name': 'Wicket', 'type': 'toon', 'alias': ['wicket'],
               'icon': 'https://swgoh.gg/static/img/assets/tex.charui_ewok_wicket.png'},
    'JEDIKNIGHTGUARDIAN': {'name': 'Jedi Knight Guardian', 'type': 'toon', 'alias': ['jedi knight guardian', 'jkg'],
                           'icon': 'https://swgoh.gg/static/img/assets/tex.charui_jedi_guardian_01.png'},
    'SAVAGEOPRESS': {'name': 'Savage Opress', 'type': 'toon', 'alias': ['savage', 'savage opress'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_savageopress.png'},
    'HOTHHAN': {'name': 'Captain Han Solo', 'type': 'toon', 'alias': ['hoth han', 'chs', 'captain han solo'],
                'icon': 'https://swgoh.gg/static/img/assets/tex.charui_hoth_han.png'},
    'CT210408': {'name': 'CT-21-0408 "Echo"', 'type': 'toon', 'alias': ['echo', 'ct-21-0408 echo'],
                 'icon': 'https://swgoh.gg/static/img/assets/tex.charui_trooperclone_echo.png'},
    'ANAKINKNIGHT': {'name': 'Jedi Knight Anakin', 'type': 'toon', 'alias': ['jedi knight anakin', 'jka'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_anakinknight.png'},
    'GEONOSIANSTARFIGHTER1': {'name': "Sun Fac's Geonosian Starfighter", 'type': 'ship',
                              'alias': ['sun fac', 'sun facs geonosian starfighter'],
                              'icon': 'https://swgoh.gg/static/img/assets/tex.charui_geonosis_fighter_sunfac.png'},
    'JYNERSO': {'name': 'Jyn Erso', 'type': 'toon', 'alias': ['jyn', 'jyn erso'],
                'icon': 'https://swgoh.gg/static/img/assets/tex.charui_jyn.png'},
    'GAUNTLETSTARFIGHTER': {'name': 'Gauntlet Starfighter', 'type': 'ship',
                            'alias': ['gauntlet', 'gauntlet starfighter'],
                            'icon': 'https://swgoh.gg/static/img/assets/tex.charui_gauntlet.png'},
    'CADBANE': {'name': 'Cad Bane', 'type': 'toon', 'alias': ['cad bane'],
                'icon': 'https://swgoh.gg/static/img/assets/tex.charui_cadbane.png'},
    'PRINCESSLEIA': {'name': 'Princess Leia', 'type': 'toon', 'alias': ['princess leia', 'leia'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_leia_princess.png'},
    'JAWA': {'name': 'Jawa', 'type': 'toon', 'alias': ['jawa'],
             'icon': 'https://swgoh.gg/static/img/assets/tex.charui_jawa_jawa.png'},
    'KANANJARRUSS3': {'name': 'Kanan Jarrus', 'type': 'toon', 'alias': ['kanan', 'kanan jarrus'],
                      'icon': 'https://swgoh.gg/static/img/assets/tex.charui_kanan_s3.png'},
    'TIEFIGHTERPILOT': {'name': 'TIE Fighter Pilot', 'type': 'toon', 'alias': ['tfp', 'tie fighter pilot'],
                        'icon': 'https://swgoh.gg/static/img/assets/tex.charui_tiepilot.png'},
    'URORRURRR': {'name': "URoRRuR'R'R", 'type': 'toon', 'alias': ['urorrurrr'],
                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_urorrurrr.png'},
    'ARC170CLONESERGEANT': {'name': "Clone Sergeant's ARC-170", 'type': 'ship',
                            'alias': ['clone sergeant', 'sergeant', 'clone sergeants arc170', 'arc170'],
                            'icon': 'https://swgoh.gg/static/img/assets/tex.charui_arc170.png'},
    'BARRISSOFFEE': {'name': 'Barriss Offee', 'type': 'toon', 'alias': ['barriss', 'barriss offee'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_barriss_light.png'},
    'NIGHTSISTERINITIATE': {'name': 'Nightsister Initiate', 'type': 'toon', 'alias': ['nightsister initiate'],
                            'icon': 'https://swgoh.gg/static/img/assets/tex.charui_nightsister_initiate.png'},
    'EZRABRIDGERS3': {'name': 'Ezra Bridger', 'type': 'toon', 'alias': ['ezra', 'ezra bridger'],
                      'icon': 'https://swgoh.gg/static/img/assets/tex.charui_ezra_s3.png'},
    'DENGAR': {'name': 'Dengar', 'type': 'toon', 'alias': ['dengar'],
               'icon': 'https://swgoh.gg/static/img/assets/tex.charui_dengar.png'},
    'VEERS': {'name': 'General Veers', 'type': 'toon', 'alias': ['veers', 'general veers'],
              'icon': 'https://swgoh.gg/static/img/assets/tex.charui_veers.png'},
    'RESISTANCETROOPER': {'name': 'Resistance Trooper', 'type': 'toon', 'alias': ['rp', 'resistance trooper'],
                          'icon': 'https://swgoh.gg/static/img/assets/tex.charui_resistancetrooper.png'},
    'K2SO': {'name': 'K-2SO', 'type': 'toon', 'alias': ['k2so'],
             'icon': 'https://swgoh.gg/static/img/assets/tex.charui_k2so.png'},
    'BB8': {'name': 'BB-8', 'type': 'toon', 'alias': ['bb8'],
            'icon': 'https://swgoh.gg/static/img/assets/tex.charui_bb8.png'},
    'EETHKOTH': {'name': 'Eeth Koth', 'type': 'toon', 'alias': ['eeth', 'eeth koth'],
                 'icon': 'https://swgoh.gg/static/img/assets/tex.charui_eethkoth.png'},
    'GRANDMOFFTARKIN': {'name': 'Grand Moff Tarkin', 'type': 'toon', 'alias': ['tarkin', 'grand moff tarkin'],
                        'icon': 'https://swgoh.gg/static/img/assets/tex.charui_tarkinadmiral.png'},
    'GHOST': {'name': 'Ghost', 'type': 'ship', 'alias': ['ghost'],
              'icon': 'https://swgoh.gg/static/img/assets/tex.charui_ghost.png'},
    'UWINGSCARIF': {'name': "Bistan's U-wing", 'type': 'ship', 'alias': ['bistans uwing', 'uwing'],
                    'icon': 'https://swgoh.gg/static/img/assets/tex.charui_uwing.png'},
    'TIEREAPER': {'name': 'TIE Reaper', 'type': 'ship', 'alias': ['tie reaper'],
                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_tiereaper.png'},
    'R2D2_LEGENDARY': {'name': 'R2-D2', 'type': 'toon', 'alias': ['r2d2', 'r2'],
                       'icon': 'https://swgoh.gg/static/img/assets/tex.charui_astromech_r2d2.png'},
    'DATHCHA': {'name': 'Dathcha', 'type': 'toon', 'alias': ['datcha'],
                'icon': 'https://swgoh.gg/static/img/assets/tex.charui_jawa_dathcha.png'},
    'IG88': {'name': 'IG-88', 'type': 'toon', 'alias': ['ig88'],
             'icon': 'https://swgoh.gg/static/img/assets/tex.charui_ig88.png'},
    'GRANDMASTERYODA': {'name': 'Grand Master Yoda', 'type': 'toon', 'alias': ['yoda', 'grandmaster yoda'],
                        'icon': 'https://swgoh.gg/static/img/assets/tex.charui_yodagrandmaster.png'},
    'IMAGUNDI': {'name': 'Ima-Gun Di', 'type': 'toon', 'alias': ['ima gundi'],
                 'icon': 'https://swgoh.gg/static/img/assets/tex.charui_imagundi.png'},
    'XWINGRESISTANCE': {'name': 'Resistance X-wing', 'type': 'ship', 'alias': ['resistance xwing'],
                        'icon': 'https://swgoh.gg/static/img/assets/tex.charui_xwing_resistance.png'},
    'FIRSTORDERTROOPER': {'name': 'First Order Stormtrooper', 'type': 'toon',
                          'alias': ['first order stormtrooper', 'fos'],
                          'icon': 'https://swgoh.gg/static/img/assets/tex.charui_firstordertrooper.png'},
    'NIGHTSISTERZOMBIE': {'name': 'Nightsister Zombie', 'type': 'toon', 'alias': ['nightsister zombie'],
                          'icon': 'https://swgoh.gg/static/img/assets/tex.charui_nightsisters_zombie.png'},
    'MILLENNIUMFALCONEP7': {'name': 'Millennium Falcon (Ep VII)', 'type': 'ship',
                            'alias': ['mf', 'millenium falcon', 'falcon'],
                            'icon': 'https://swgoh.gg/static/img/assets/tex.charui_mfalcon_ep7.png'},
    'HERASYNDULLAS3': {'name': 'Hera Syndulla', 'type': 'toon', 'alias': ['hera', 'hera syndulla'],
                       'icon': 'https://swgoh.gg/static/img/assets/tex.charui_hera_s3.png'},
    'HOTHREBELSCOUT': {'name': 'Hoth Rebel Scout', 'type': 'toon', 'alias': ['hrs', 'hoth rebel scout', 'hoth'],
                       'icon': 'https://swgoh.gg/static/img/assets/tex.charui_rebelhothscout.png'},
    'LUMINARAUNDULI': {'name': 'Luminara Unduli', 'type': 'toon', 'alias': ['luminara unduli', 'luminara'],
                       'icon': 'https://swgoh.gg/static/img/assets/tex.charui_luminara.png'},
    'CAPITALMONCALAMARICRUISER': {'name': 'Home One', 'type': 'ship', 'alias': ['home one'],
                                  'icon': 'https://swgoh.gg/static/img/assets/tex.charui_moncalamarilibertycruiser.png'}
    ,
    'CAPITALSTARDESTROYER': {'name': 'Executrix', 'type': 'ship', 'alias': ['executrix'],
                             'icon': 'https://swgoh.gg/static/img/assets/tex.charui_stardestroyer.png'},
    'BOBAFETT': {'name': 'Boba Fett', 'type': 'toon', 'alias': ['boba', 'boba fett'],
                 'icon': 'https://swgoh.gg/static/img/assets/tex.charui_bobafett.png'},
    'CASSIANANDOR': {'name': 'Cassian Andor', 'type': 'toon', 'alias': ['cassian', 'cassian andor'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_cassian.png'},
    'JEDISTARFIGHTERCONSULAR': {'name': "Jedi Consular's Starfighter", 'type': 'ship',
                                'alias': ['jedi consulars starfighter'],
                                'icon': 'https://swgoh.gg/static/img/assets/tex.charui_jedi_fighter.png'},
    'BLADEOFDORIN': {'name': "Plo Koon's Jedi Starfighter", 'type': 'ship',
                     'alias': ['plo koons jedi starfighter', 'plo koon'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_jedi_fighter_bladeofdorin.png'},
    'FIRSTORDEROFFICERMALE': {'name': 'First Order Officer', 'type': 'toon', 'alias': ['foo', 'first order officer'],
                              'icon': 'https://swgoh.gg/static/img/assets/tex.charui_firstorderofficer.png'},
    'DIRECTORKRENNIC': {'name': 'Director Krennic', 'type': 'toon', 'alias': ['krennic', 'director krennic'],
                        'icon': 'https://swgoh.gg/static/img/assets/tex.charui_krennic.png'},
    'IG86SENTINELDROID': {'name': 'IG-86 Sentinel Droid', 'type': 'toon', 'alias': ['ig86', 'ig86 sentinel droid'],
                          'icon': 'https://swgoh.gg/static/img/assets/tex.charui_ig86.png'},
    'TEEBO': {'name': 'Teebo', 'type': 'toon', 'alias': ['teebo'],
              'icon': 'https://swgoh.gg/static/img/assets/tex.charui_ewok_teebo.png'},
    'GENERALKENOBI': {'name': 'General Kenobi', 'type': 'toon', 'alias': ['gk', 'general kenobi', 'kenobi'],
                      'icon': 'https://swgoh.gg/static/img/assets/tex.charui_obiwangeneral.png'},
    'FULCRUMAHSOKA': {'name': 'Ahsoka Tano (Fulcrum)', 'type': 'toon',
                      'alias': ['ahsoka tano fulcrum', 'fulcrum', 'atf', 'hotsoka'],
                      'icon': 'https://swgoh.gg/static/img/assets/tex.charui_ahsokaadult.png'},
    'ADMIRALACKBAR': {'name': 'Admiral Ackbar', 'type': 'toon', 'alias': ['ackbar', 'admiral ackbar', 'aa'],
                      'icon': 'https://swgoh.gg/static/img/assets/tex.charui_ackbaradmiral.png'},
    'LOGRAY': {'name': 'Logray', 'type': 'toon', 'alias': ['logray'],
               'icon': 'https://swgoh.gg/static/img/assets/tex.charui_ewok_logray.png'},
    'IMPERIALSUPERCOMMANDO': {'name': 'Imperial Super Commando', 'type': 'toon',
                              'alias': ['imperial super commando', 'isc'],
                              'icon': 'https://swgoh.gg/static/img/assets/tex.charui_imperial_super_commando.png'},
    'GEONOSIANSTARFIGHTER3': {'name': "Geonosian Spy's Starfighter", 'type': 'ship',
                              'alias': ['geonosian spys starfighter', 'geonosian spy'],
                              'icon': 'https://swgoh.gg/static/img/assets/tex.charui_geonosis_fighter_spy.png'},
    'GEONOSIANSTARFIGHTER2': {'name': "Geonosian Soldier's Starfighter", 'type': 'ship',
                              'alias': ['geonosian soldiers starfighter', 'geonosian soldier'],
                              'icon': 'https://swgoh.gg/static/img/assets/tex.charui_geonosis_fighter_soldier.png'},
    'NUTEGUNRAY': {'name': 'Nute Gunray', 'type': 'toon', 'alias': ['nute gunray', 'nute'],
                   'icon': 'https://swgoh.gg/static/img/assets/tex.charui_nutegunray.png'},
    'NIGHTSISTERACOLYTE': {'name': 'Nightsister Acolyte', 'type': 'toon', 'alias': ['nightsister acolyte'],
                           'icon': 'https://swgoh.gg/static/img/assets/tex.charui_nightsister_acolyte.png'},
    'SABINEWRENS3': {'name': 'Sabine Wren', 'type': 'toon', 'alias': ['sabine wren', 'sabine'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_sabine_s3.png'},
    'SMUGGLERHAN': {'name': 'Veteran Smuggler Han Solo', 'type': 'toon',
                    'alias': ['veteran smuggler han solo', 'veteran han', 'vshs', 'han', 'han solo'],
                    'icon': 'https://swgoh.gg/static/img/assets/tex.charui_tfa_han.png'},
    'POE': {'name': 'Poe Dameron', 'type': 'toon', 'alias': ['poe', 'poe dameron'],
            'icon': 'https://swgoh.gg/static/img/assets/tex.charui_poe.png'},
    'MAGMATROOPER': {'name': 'Magmatrooper', 'type': 'toon', 'alias': ['magma trooper'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_trooperstorm_magma.png'},
    'COMMANDSHUTTLE': {'name': "Kylo Ren's Command Shuttle", 'type': 'ship', 'alias': ['command shuttle'],
                       'icon': 'https://swgoh.gg/static/img/assets/tex.charui_upsilon_shuttle_kylo.png'},
    'CHIEFCHIRPA': {'name': 'Chief Chirpa', 'type': 'toon', 'alias': ['chief chirpa', 'chirpa'],
                    'icon': 'https://swgoh.gg/static/img/assets/tex.charui_ewok_chirpa.png'},
    'PAPLOO': {'name': 'Paploo', 'type': 'toon', 'alias': ['paploo'],
               'icon': 'https://swgoh.gg/static/img/assets/tex.charui_ewok_paploo.png'},
    'CLONESERGEANTPHASEI': {'name': 'Clone Sergeant - Phase I', 'type': 'toon',
                            'alias': ['clone sergeant phase i', 'clone sergeant'],
                            'icon': 'https://swgoh.gg/static/img/assets/tex.charui_trooperclonegreen.png'},
    'KITFISTO': {'name': 'Kit Fisto', 'type': 'toon', 'alias': ['kit fisto'],
                 'icon': 'https://swgoh.gg/static/img/assets/tex.charui_kitfisto.png'},
    'GARSAXON': {'name': 'Gar Saxon', 'type': 'toon', 'alias': ['gar saxon'],
                 'icon': 'https://swgoh.gg/static/img/assets/tex.charui_gar_saxon.png'},
    'UWINGROGUEONE': {'name': "Cassian's U-wing", 'type': 'ship', 'alias': ['uwing', 'cassians uwing'],
                      'icon': 'https://swgoh.gg/static/img/assets/tex.charui_uwing_hero.png'},
    'CT5555': {'name': 'CT-5555 "Fives"', 'type': 'toon', 'alias': ['fives', 'five', 'ct5555 fives'],
               'icon': 'https://swgoh.gg/static/img/assets/tex.charui_trooperclone_fives.png'},
    'GREEDO': {'name': 'Greedo', 'type': 'toon', 'alias': ['greedo'],
               'icon': 'https://swgoh.gg/static/img/assets/tex.charui_greedo.png'},
    'WEDGEANTILLES': {'name': 'Wedge Antilles', 'type': 'toon', 'alias': ['wedge', 'wedge antilles'],
                      'icon': 'https://swgoh.gg/static/img/assets/tex.charui_rebelpilot_wedge.png'},
    'SUNFAC': {'name': 'Sun Fac', 'type': 'toon', 'alias': ['sun fac'],
               'icon': 'https://swgoh.gg/static/img/assets/tex.charui_geonosian_sunfac.png'},
    'CAPITALCHIMAERA': {'name': 'Chimaera', 'type': 'ship', 'alias': ['chimaera'],
                        'icon': 'https://swgoh.gg/static/img/assets/tex.charui_chimaera.png'},
    'GRANDADMIRALTHRAWN': {'name': 'Grand Admiral Thrawn', 'type': 'toon', 'alias': ['thrawn', 'grand admiral thrawn'],
                           'icon': 'https://swgoh.gg/static/img/assets/tex.charui_thrawn.png'},
    'UMBARANSTARFIGHTER': {'name': 'Umbaran Starfighter', 'type': 'ship', 'alias': ['umbaran starfighter'],
                           'icon': 'https://swgoh.gg/static/img/assets/tex.charui_umbaran_star_fighter.png'},
    'BAZEMALBUS': {'name': 'Baze Malbus', 'type': 'toon', 'alias': ['baze', 'baze malbus'],
                   'icon': 'https://swgoh.gg/static/img/assets/tex.charui_bazemalbus.png'},
    'B2SUPERBATTLEDROID': {'name': 'B2 Super Battle Droid', 'type': 'toon', 'alias': ['b2', 'bé super battle droid'],
                           'icon': 'https://swgoh.gg/static/img/assets/tex.charui_b2.png'},
    'DEATHTROOPER': {'name': 'Death Trooper', 'type': 'toon', 'alias': ['death trooper'],
                     'icon': 'https://swgoh.gg/static/img/assets/tex.charui_trooperdeath.png'},
    'TALIA': {'name': 'Talia', 'type': 'toon', 'alias': ['talia'],
              'icon': 'https://swgoh.gg/static/img/assets/tex.charui_nightsister_talia.png'},
    'FIRSTORDERTIEPILOT': {'name': 'First Order TIE Pilot', 'type': 'toon', 'alias': ['first order tie pilot', 'fotp'],
                           'icon': 'https://swgoh.gg/static/img/assets/tex.charui_firstordertiepilot.png'},
    'VADER': {'name': 'Darth Vader', 'type': 'toon', 'alias': ['vader', 'darth vader', 'lord vader', 'death by tray'],
              'icon': 'https://swgoh.gg/static/img/assets/tex.charui_vader.png'},
    'STORMTROOPERHAN': {'name': 'Stormtrooper Han', 'type': 'toon',
                        'alias': ['sthan', 'stromtrooper han', 'han', 'han solo'],
                        'icon': 'https://swgoh.gg/static/img/assets/tex.charui_trooperstorm_han.png'},
    'HANSOLO': {'name': 'Han Solo', 'type': 'toon', 'alias': ['oghan', 'han solo', 'han', 'raid han'],
                'icon': 'https://swgoh.gg/static/img/assets/tex.charui_han.png'}
}
